"""
35-period demand generator

"""

import numpy as np
import matplotlib.pyplot as plt
from input_data import (
    PARTS, END_PRODUCT, BOM, LEAD_TIME, MIN_LOT, INIT_INV,
    SETUP_COST, HOLDING_COST, BACKORDER_COST,
    DEMAND_FORECAST, DEMAND_REALIZED
)

#  Original 30-week data 
weeks_observed = np.arange(1, 31)
forecast_30 = np.array(DEMAND_FORECAST)
realized_30 = np.array(DEMAND_REALIZED)
weeks_future = np.arange(31, 36)

#  Method 1: Linear extrapolation 
a_f, b_f = np.polyfit(weeks_observed, forecast_30, 1)
a_r, b_r = np.polyfit(weeks_observed, realized_30, 1)

linear_forecast = [int(round(a_f * w + b_f)) for w in weeks_future]
linear_realized = [int(round(a_r * w + b_r)) for w in weeks_future]

#  Method 2: Cyclic (repeat weeks 1-5) 
cyclic_forecast = [int(v) for v in forecast_30[:5]]
cyclic_realized = [int(v) for v in realized_30[:5]]

#  Print comparison to terminal 
print("=" * 70)
print("35-PERIOD DEMAND GENERATION: LINEAR vs CYCLIC")
print("=" * 70)
print(f"\nLinear regression:")
print(f"  Forecast: y = {a_f:+.3f} * x + {b_f:.2f}")
print(f"  Realized: y = {a_r:+.3f} * x + {b_r:.2f}")
print(f"\n{'Week':<6}{'Lin Fcst':>10}{'Lin Real':>10}{'Cyc Fcst':>10}{'Cyc Real':>10}")
print("-" * 46)
for i, w in enumerate(weeks_future):
    print(f"{w:<6}{linear_forecast[i]:>10}{linear_realized[i]:>10}"
          f"{cyclic_forecast[i]:>10}{cyclic_realized[i]:>10}")

print(f"\nGap (realized - forecast) per method:")
lin_gaps = [linear_realized[i] - linear_forecast[i] for i in range(5)]
cyc_gaps = [cyclic_realized[i] - cyclic_forecast[i] for i in range(5)]
print(f"  Linear:  {lin_gaps}  (avg {np.mean(lin_gaps):+.1f})")
print(f"  Cyclic:  {cyc_gaps}  (avg {np.mean(cyc_gaps):+.1f})")

#  Build full 35-week lists 
linear_forecast_35 = [int(v) for v in forecast_30] + linear_forecast
linear_realized_35 = [int(v) for v in realized_30] + linear_realized
cyclic_forecast_35 = [int(v) for v in forecast_30] + cyclic_forecast
cyclic_realized_35 = [int(v) for v in realized_30] + cyclic_realized

#  Write input files 
def fmt_dict(d, indent=4):
    pad = " " * indent
    lines = [f"{pad}{k!r}: {v!r}," for k, v in d.items()]
    return "{\n" + "\n".join(lines) + "\n}"

def fmt_list_chunked(lst, per_row=10, indent=4):
    pad = " " * indent
    rows = []
    for i in range(0, len(lst), per_row):
        chunk = lst[i:i + per_row]
        rows.append(pad + ", ".join(str(v) for v in chunk))
    return "[\n" + ",\n".join(rows) + "\n]"

def write_input_file(filename, method_desc, forecast_35, realized_35):
    content = f'''# {filename}
# AUTO-GENERATED by 35periods_generator.py - do not edit by hand.
# Original 30-week data (weeks 1-30) plus 5 extra weeks (31-35).
# Method: {method_desc}

# Parts
PARTS = {PARTS!r}
END_PRODUCT = {END_PRODUCT!r}
T = 35  # number of periods (extended from 30)

# Bill of Materials (parent: {{child: qty}})
BOM = {fmt_dict(BOM)}

# Lead times (periods)
LEAD_TIME = {fmt_dict(LEAD_TIME)}

# Minimum lot sizes
MIN_LOT = {fmt_dict(MIN_LOT)}

# Beginning inventory
INIT_INV = {fmt_dict(INIT_INV)}

# Setup costs (EUR/setup)
SETUP_COST = {fmt_dict(SETUP_COST)}

# Holding costs (EUR/week/unit)
HOLDING_COST = {fmt_dict(HOLDING_COST)}

# Forecasted demand (weeks 1-35; weeks 31-35 {method_desc})
DEMAND_FORECAST = {fmt_list_chunked(forecast_35)}

# Realized demand (weeks 1-35; weeks 31-35 {method_desc})
DEMAND_REALIZED = {fmt_list_chunked(realized_35)}

# Backorder cost
BACKORDER_COST = {BACKORDER_COST}
'''
    with open(filename, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"\n>>> Written: {filename}")

write_input_file(
    "input_data_35periods_linear.py",
    "linear extrapolation (least-squares regression on weeks 1-30)",
    linear_forecast_35,
    linear_realized_35
)

write_input_file(
    "input_data_35periods_cyclic.py",
    "cyclic repetition (weeks 1-5 repeated)",
    cyclic_forecast_35,
    cyclic_realized_35
)

#  Comparison plot 
fig, axes = plt.subplots(2, 1, figsize=(12, 7), sharex=True)

weeks_all = np.arange(1, 36)

# Top plot: Forecast
ax = axes[0]
ax.scatter(weeks_observed, forecast_30, color='#888780', s=30, zorder=3,
           label='Observed (week 1-30)')
ax.scatter(weeks_future, linear_forecast, color='#1D9E75', marker='D', s=60,
           zorder=4, label='Linear extrapolation')
ax.scatter(weeks_future, cyclic_forecast, color='#D85A30', marker='s', s=60,
           zorder=4, label='Cyclic (weeks 1-5)')
# trend line
trend_f = a_f * weeks_all + b_f
ax.plot(weeks_all, trend_f, color='#1D9E75', linestyle='--', linewidth=1, alpha=0.5)
ax.axvline(x=30.5, color='gray', linestyle=':', linewidth=1)
ax.set_ylabel('Forecasted demand (units)')
ax.set_title('Forecasted demand: linear vs cyclic extrapolation')
ax.legend(loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)

# Bottom plot: Realized
ax = axes[1]
ax.scatter(weeks_observed, realized_30, color='#888780', s=30, zorder=3,
           label='Observed (week 1-30)')
ax.scatter(weeks_future, linear_realized, color='#1D9E75', marker='D', s=60,
           zorder=4, label='Linear extrapolation')
ax.scatter(weeks_future, cyclic_realized, color='#D85A30', marker='s', s=60,
           zorder=4, label='Cyclic (weeks 1-5)')
# trend line
trend_r = a_r * weeks_all + b_r
ax.plot(weeks_all, trend_r, color='#1D9E75', linestyle='--', linewidth=1, alpha=0.5)
ax.axvline(x=30.5, color='gray', linestyle=':', linewidth=1)
ax.set_xlabel('Week')
ax.set_ylabel('Realized demand (units)')
ax.set_title('Realized demand: linear vs cyclic extrapolation')
ax.legend(loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)

plt.tight_layout()
PLOT_FILE = "extrapolation_comparison.png"
plt.savefig(PLOT_FILE, dpi=150, bbox_inches='tight')
plt.close(fig)
print(f">>> Plot saved: {PLOT_FILE}")