"""
Demand extrapolation generator
==============================
Reads the 30-week demand data from input_data.py, fits a linear
regression to both forecast and realized demand, extrapolates 5
extra weeks, and writes a new input_data_35periods.py file with
35 weeks.

Also saves a visualization of the extrapolation as a PNG.
"""

import numpy as np
import matplotlib.pyplot as plt
from input_data import (
    PARTS, END_PRODUCT, BOM, LEAD_TIME, MIN_LOT, INIT_INV,
    SETUP_COST, HOLDING_COST, BACKORDER_COST,
    DEMAND_FORECAST, DEMAND_REALIZED
)

# ─── Linear regression on the 30-week data ────────────────────────────
weeks_observed = np.arange(1, 31)
forecast_30 = np.array(DEMAND_FORECAST)
realized_30 = np.array(DEMAND_REALIZED)

a_f, b_f = np.polyfit(weeks_observed, forecast_30, 1)
a_r, b_r = np.polyfit(weeks_observed, realized_30, 1)

# ─── Predict weeks 31 through 35 ──────────────────────────────────────
weeks_future = np.arange(31, 36)
forecast_future = [int(round(a_f * w + b_f)) for w in weeks_future]
realized_future = [int(round(a_r * w + b_r)) for w in weeks_future]

# ─── Print results to terminal ────────────────────────────────────────
print("=" * 60)
print("LINEAR EXTRAPOLATION TO 35 WEEKS")
print("=" * 60)
print(f"\nForecast trend:  y = {a_f:+.3f} * x + {b_f:.2f}")
print(f"Realized trend:  y = {a_r:+.3f} * x + {b_r:.2f}")
print(f"\n{'Week':<6}{'Forecast':>12}{'Realized':>12}")
print("-" * 30)
for i, w in enumerate(weeks_future):
    print(f"{w:<6}{forecast_future[i]:>12}{realized_future[i]:>12}")

# ─── Build full 35-week lists ─────────────────────────────────────────
DEMAND_FORECAST_35 = [int(v) for v in forecast_30] + forecast_future
DEMAND_REALIZED_35 = [int(v) for v in realized_30] + realized_future

# ─── Write input_data_35periods.py ────────────────────────────────────
def fmt_dict(d, indent=4):
    """Format a dict as a nicely indented multi-line literal."""
    pad = " " * indent
    lines = [f"{pad}{k!r}: {v!r}," for k, v in d.items()]
    return "{\n" + "\n".join(lines) + "\n}"

def fmt_list_chunked(lst, per_row=10, indent=4):
    """Format a list with line breaks every per_row items."""
    pad = " " * indent
    rows = []
    for i in range(0, len(lst), per_row):
        chunk = lst[i:i + per_row]
        rows.append(pad + ", ".join(str(v) for v in chunk))
    return "[\n" + ",\n".join(rows) + "\n]"

OUTPUT_FILE = "input_data_35periods.py"

content = f'''# input_data_35periods.py
# AUTO-GENERATED by 35periods_generator.py - do not edit by hand.
# Original 30-week data (weeks 1-30) plus 5 extrapolated weeks (31-35),
# obtained via linear least-squares regression on the 30-week series.
#
# Forecast trend:  y = {a_f:+.3f} * x + {b_f:.2f}
# Realized trend:  y = {a_r:+.3f} * x + {b_r:.2f}

# Parts
PARTS = {PARTS!r}
END_PRODUCT = {END_PRODUCT!r}
T = 35  # number of periods (extended from 30)

# Bill of Materials (parent: {{child: qty}})
BOM = {fmt_dict(BOM)}

# Lead times (periods)
LEAD_TIME = {fmt_dict(LEAD_TIME)}

# Minimum lot sizes
MIN_LOT = {fmt_dict(MIN_LOT)}

# Beginning inventory
INIT_INV = {fmt_dict(INIT_INV)}

# Setup costs (EUR/setup)
SETUP_COST = {fmt_dict(SETUP_COST)}

# Holding costs (EUR/week/unit)
HOLDING_COST = {fmt_dict(HOLDING_COST)}

# Forecasted demand (weeks 1-35; weeks 31-35 extrapolated)
DEMAND_FORECAST = {fmt_list_chunked(DEMAND_FORECAST_35)}

# Realized demand (weeks 1-35; weeks 31-35 extrapolated)
DEMAND_REALIZED = {fmt_list_chunked(DEMAND_REALIZED_35)}

# Backorder cost
BACKORDER_COST = {BACKORDER_COST}
'''

with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    f.write(content)

print(f"\n>>> Written: {OUTPUT_FILE}")

# ─── Visualization (saved as PNG, not shown) ──────────────────────────
fig, axes = plt.subplots(2, 1, figsize=(11, 7), sharex=True)

weeks_all = np.arange(1, 36)
trend_f = a_f * weeks_all + b_f
trend_r = a_r * weeks_all + b_r

# ── Top plot: Forecast ──
ax = axes[0]
ax.scatter(weeks_observed, forecast_30, color='#378ADD', s=35, zorder=3,
           label='Forecast (week 1-30)')
ax.plot(weeks_all, trend_f, color='#D85A30', linestyle='--', linewidth=1.5,
        label=f'Trend line  (slope={a_f:+.2f})')
ax.scatter(weeks_future, forecast_future, color='#1D9E75', marker='D', s=60,
           zorder=4, label='Extrapolation (week 31-35)')
ax.axvline(x=30.5, color='gray', linestyle=':', linewidth=1)
ax.set_ylabel('Forecasted demand (units)')
ax.set_title('Forecasted demand: 30 weeks of data + linear extrapolation')
ax.legend(loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)

# ── Bottom plot: Realized ──
ax = axes[1]
ax.scatter(weeks_observed, realized_30, color='#378ADD', s=35, zorder=3,
           label='Realized (week 1-30)')
ax.plot(weeks_all, trend_r, color='#D85A30', linestyle='--', linewidth=1.5,
        label=f'Trend line  (slope={a_r:+.2f})')
ax.scatter(weeks_future, realized_future, color='#1D9E75', marker='D', s=60,
           zorder=4, label='Extrapolation (week 31-35)')
ax.axvline(x=30.5, color='gray', linestyle=':', linewidth=1)
ax.set_xlabel('Week')
ax.set_ylabel('Realized demand (units)')
ax.set_title('Realized demand: 30 weeks of data + linear extrapolation')
ax.legend(loc='upper left', fontsize=9)
ax.grid(True, alpha=0.3)

plt.tight_layout()

PLOT_FILE = "extrapolation_plot.png"
plt.savefig(PLOT_FILE, dpi=150, bbox_inches='tight')
plt.close(fig)
print(f">>> Plot saved: {PLOT_FILE}")